use_frameworks!

target 'Vandelay_Example' do
  pod 'Vandelay', :path => '../Vandelay'
  pod 'VandelayDropbox', :path => '../VandelayDropbox'

  target 'Vandelay_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
  end
end
