use_frameworks!

target 'Vandelay_Example' do
  pod 'Vandelay', :path => '../'
  pod 'VandelayDropbox', :path => '../'
  #pod 'VandelayQr', :path => '../'
  
  target 'Vandelay_Tests' do
    inherit! :search_paths
  end
end
